# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "car_query"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Orlando Del Aguila"]
  s.date = "2012-04-28"
  s.description = "A Ruby wrapper for the www.carqueryapi.com's JSON API"
  s.email = "me@orlandodelaguila.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/car_query.rb",
    "spec/car_query_spec.rb",
    "spec/fixtures/vcr_cassettes/CarQuery.yml",
    "spec/fixtures/vcr_cassettes/CarQuery_Makes.yml",
    "spec/fixtures/vcr_cassettes/CarQuery_Models.yml",
    "spec/fixtures/vcr_cassettes/CarQuery_Trims.yml",
    "spec/fixtures/vcr_cassettes/CarQuery_Years.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/orlandodelaguila/car_query"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Ruby wrapper for the www.carqueryapi.com's JSON API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.9"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.2.7"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.6"])
      s.add_development_dependency(%q<ZenTest>, ["~> 4.7.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.9.0"])
      s.add_development_dependency(%q<vcr>, ["~> 2.1.1"])
      s.add_development_dependency(%q<webmock>, ["~> 1.8.6"])
    else
      s.add_dependency(%q<rake>, [">= 0.9"])
      s.add_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_dependency(%q<addressable>, ["~> 2.2.7"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, ["~> 0.6"])
      s.add_dependency(%q<ZenTest>, ["~> 4.7.0"])
      s.add_dependency(%q<rspec>, ["~> 2.9.0"])
      s.add_dependency(%q<vcr>, ["~> 2.1.1"])
      s.add_dependency(%q<webmock>, ["~> 1.8.6"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.9"])
    s.add_dependency(%q<httparty>, ["~> 0.8.3"])
    s.add_dependency(%q<addressable>, ["~> 2.2.7"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, ["~> 0.6"])
    s.add_dependency(%q<ZenTest>, ["~> 4.7.0"])
    s.add_dependency(%q<rspec>, ["~> 2.9.0"])
    s.add_dependency(%q<vcr>, ["~> 2.1.1"])
    s.add_dependency(%q<webmock>, ["~> 1.8.6"])
  end
end

